/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mvc;



/**
 *
 * @author sandro.santini
 */
public class BarraN extends javax.swing.JPanel {

    private Control ctrl;
    private View view;

    /**
     * Define a instalacia de Dontrol e de view que a BarraN vai usar
     * como é usada em uma classe que implementa View normalmente o preenchimento
     * fica this.barraN1.setBarraN(ctrl, this);
     * @param ctrl Instancia da classe control
     * @param view Instanca da classe view
     */
    public void setBarraN(Control ctrl, View view) {
        this.ctrl = ctrl;
        this.view = view;
    }

    public BarraN() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jVoltar = new javax.swing.JButton();
        jAvancar = new javax.swing.JButton();
        jNovo = new javax.swing.JButton();
        jExcluir = new javax.swing.JButton();
        jEditar = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jVoltar.setText("<");
        jVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVoltarActionPerformed(evt);
            }
        });
        add(jVoltar);

        jAvancar.setText(">");
        jAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAvancarActionPerformed(evt);
            }
        });
        add(jAvancar);

        jNovo.setText("+");
        jNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNovoActionPerformed(evt);
            }
        });
        add(jNovo);

        jExcluir.setText("-");
        jExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExcluirActionPerformed(evt);
            }
        });
        add(jExcluir);

        jEditar.setText("e");
        jEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditarActionPerformed(evt);
            }
        });
        add(jEditar);
    }// </editor-fold>//GEN-END:initComponents

    private void jVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVoltarActionPerformed
        ctrl.voltar();
        view.modelView(ctrl.exibir());
    }//GEN-LAST:event_jVoltarActionPerformed

    private void jAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAvancarActionPerformed
        ctrl.avancar();
        view.modelView(ctrl.exibir());
    }//GEN-LAST:event_jAvancarActionPerformed

    private void jNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNovoActionPerformed
       if (this.jNovo.getText()=="+"){
           view.clearView();
           this.jNovo.setText("*");
       }
       else{
           ctrl.adicionar(view.viewModel());
           this.jNovo.setText("+");
           
       }
    }//GEN-LAST:event_jNovoActionPerformed

    private void jEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditarActionPerformed
        ctrl.editar(view.viewModel());
    }//GEN-LAST:event_jEditarActionPerformed

    private void jExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExcluirActionPerformed
        ctrl.excluir();
        ctrl.voltar();
        view.modelView(ctrl.exibir());
    }//GEN-LAST:event_jExcluirActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAvancar;
    private javax.swing.JButton jEditar;
    private javax.swing.JButton jExcluir;
    private javax.swing.JButton jNovo;
    private javax.swing.JButton jVoltar;
    // End of variables declaration//GEN-END:variables
}
